apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-database
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/toannd135/typ-database.git'
      targetRevision: HEAD
      ref: values
      path: 'database-chart'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: typ-app
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true