apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend-chart.fullname" . }}-database-connection
type: Opaque
stringData:
  MYSQL_HOST: "argocd-database-database-chart"
  {{- with .Values.secret }}
  MYSQL_PORT: {{ index . "mysql-port" | quote }}
  MYSQL_DATABASE: {{ index . "mysql-database" | quote }}
  MYSQL_USERNAME: {{ index . "mysql-username" | quote }}
  MYSQL_PASSWORD: {{ index . "mysql-password" | quote }}
  {{- end }}